services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    PoPSchema\DirectiveCommons\FeedbackItemProviders\:
        resource: '../src/FeedbackItemProviders/*'
